### ISSUE TITLE
Code for real-world implementation

### ISSUE THREAD

**Issue by yijionglin** [HaojHuang/Edge-Grasp-Network#2]
Hi there,

Thanks for sharing such a well-developed project!

Just wondering if you have any plans to open-source the code for real-world implementation.

All the best,

**Comment by HaojHuang** [comment]
Hi,

Thanks for showing interest here. I might manage to get the code published when get a chance. The real-experiment code is built on [VGN](https://github.com/ethz-asl/vgn/tree/corl2020). Please check it if needed.

Thanks,
Haojie
